### PR TITLE
Add readiness/liveness probe for k8s deployment

### PR DESCRIPTION
**Pull request by yuanying**

### CODE REVIEW

**Comment by SISheogorath** [comment]
Are you running this in production? (As I don't run K8s myself in a setup to test this.)

**Comment by yuanying** [comment]
Yea, I'm using this chart for my private cluster.
BTW, Should this chart move k8s official chart repository?

**Comment by SISheogorath** [comment]
It would be really helpful. Would you like to contribute it there and link the PR in an issue? So we can remove it here once it's there and simplify the process for us and K8s users.

**Comment by yuanying** [comment]
@SISheogorath Hi, I uploaded this chart to kubernetes/charts repository. Could you check this?

-   https://github.com/kubernetes/charts/pull/3570

Thanks.

**Comment by SISheogorath** [comment]
Thanks for your work!

All further details: https://github.com/hackmdio/docker-hackmd#kubernetes

**Pull request closed without merging**
