### PR TITLE
Add warning for not persistent local data storage

### PR DESCRIPTION
**Pull request by SISheogorath**

### CODE REVIEW

**Comment by SISheogorath** [comment]
Maybe add additional sleep timer and instruction of fixing.

**Comment by jackycute** [comment]
Yeah, I think we need more instruction to tell how to add volume

**Comment by SISheogorath** [comment]
Added link with current docker instructions for handling data in container

**Comment by jackycute** [comment]
OK, I think we're good here.
Thanks @SISheogorath

**Pull request merged**
